project:
  type: website

website:
  title: "open-cloud-map"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 0_setup.qmd
      - 1_data.qmd
      - 2_process.qmd
      - 3_map.qmd
      - 4_cloud.qmd
      - 5_collect.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true