project:
  type: website

website:
  title: "Open Cloud Mapping"
  page-footer:
    center: SCGIS Vancouver, Canada (2026)
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 0_setup.qmd
      - 1_data.qmd
      - 2_process.qmd
      - 3_map.qmd
      - 4_cloud.qmd
      - 5_collect.qmd
    tools:
      - icon: envelope
        href: mailto:scgis.canada.vancouver@gmail.com
        text: "Email the chapter representatives"
      - icon: instagram
        href: https://instagram.com/scgis.vancouver
        text: "Follow us on Instagram"
      - icon: github
        href: https://github.com/scgis-canada-vancouver
        text: "Follow our Github organization"
      - icon: linkedin
        href: https://www.linkedin.com/company/scgis-canada-vancouver
        text: Follow us on Linkedin

format:
  html:
    theme:
      - brite
    css: styles.css
    toc: true